Save pickle file
NTD-Modelling-Consortium/ntd-model-sch pull request #73
Opened 2024-08-06 16:13 UTC by thk123

Added support to be able to write out the pickle file that is generated at the end of the simulation. 

The new tests do work, but the tests currently fail due to changes made in #70 (which this will merge into). 

@RaihaTuiTaura - if you end up running the near term simulations (e.g. up to 2026) for STH this will be useful for making sure we save the pickle files at the end so we can easily resume for the full projections.

2024-08-13 11:12 UTC, RaihaTuiTaura requested changes
All looks good, we just need to be able to add IU code to the name of the pickle file.

2024-08-13 11:12 UTC, RaihaTuiTaura commented on sch_simulation/amis_integration/amis_integration.py
> +            with open(f"final_state_{index}.pickle", "wb") as pickle_file:
Could another input be added to the `fixed_parameters` object in R to define the prefix of the pickle file name? We will be saving the pickle files for each IU so need to be able to differentiate the files.

2024-08-13 16:17 UTC, thk123 commented on sch_simulation/amis_integration/amis_integration.py
> +            with open(f"final_state_{index}.pickle", "wb") as pickle_file:
I ended up not putting it in fixed parameters as that felt more like the place for the model configuration, but hopefully you can [see by the test](https://github.com/NTD-Modelling-Consortium/ntd-model-sch/pull/73/commits/84fbb6a152755b49a0553fa3c9df363cf21f323b#diff-b8915be719adad6c6f6d6e94ef3d4bfb1a4f00924b87be2f8b04caa0da99ee9cR82-R84) how you'd specify both a custom name and also a absolute or relative directory path where you want the output to go. Of course let me know if you need help.

2024-08-14 08:11 UTC, RaihaTuiTaura approved these changes
Looks good, thanks Thomas!

2024-08-15 09:06 UTC, merged