Collect AMIS & NTDMC branches
NTD-Modelling-Consortium/ntd-model-sch pull request #88
Opened 2024-10-21 21:46 UTC by igorclark

1. add 2024-10 SCH parameter files into `run-amis-fitting` branch & (keep STH param changes)
1. merge NTDMC-file functions from `master`
2. reset python version to 3.10.9

2024-10-22 08:20 UTC, mattg3004 commented on sch_simulation/data/SCH_params/202410b-20241021/haematobium_params.txt
> +nYears	39		Number of years to run
for the projections from 2026, this should be 14 years

2024-10-22 08:20 UTC, mattg3004 commented on sch_simulation/data/SCH_params/202410b-20241021/mansoni_high_burden_params.txt
> +nYears	39		Number of years to run
Should be 14

2024-10-22 08:21 UTC, mattg3004 commented on sch_simulation/data/SCH_params/haematobium_params.txt
> +nYears	39		Number of years to run
-> 14

2024-10-22 08:22 UTC, mattg3004 commented on sch_simulation/data/SCH_params/haematobium_params.txt
> +#### Haematobium parameter values.
which files are being use for the runs? If it is the parameters in the 
`SCH_params/202410b-20241021/` folder, then these files don't really matter for now.

2024-10-22 08:23 UTC, mattg3004 commented on sch_simulation/data/SCH_params/haematobium_params.txt
> +drugEff2	0					Drug efficacy  drug 2
If these files aren't being used now, then there is no reason to change this. Otherwise, I suppose it should be 0.99 based on the other files

2024-10-22 08:24 UTC, mattg3004 commented on sch_simulation/data/SCH_params/mansoni_high_burden_params.txt
> +nYears	39		Number of years to run
-> 14

2024-10-22 08:24 UTC, mattg3004 commented on sch_simulation/data/SCH_params/mansoni_high_burden_params.txt
> +drugEff2	0					Drug efficacy  drug 2
->0.99

2024-10-22 08:24 UTC, mattg3004 commented on sch_simulation/data/SCH_params/mansoni_low_burden_params.txt
> +nYears	39		Number of years to run
-> 14

2024-10-22 08:25 UTC, mattg3004 commented on sch_simulation/data/SCH_params/mansoni_low_burden_params.txt
> +drugEff2	0					Drug efficacy  drug 2
-> 0.99

2024-10-22 08:30 UTC, mattg3004 commented on sch_simulation/data/STH_params/ascaris_params_projections.txt
> +#### Ascaris parameter values.
Do we need to update the STH_params with this PR, since these aren't being run here.

2024-10-22 08:32 UTC, mattg3004 requested changes
The `nYears` parameter in the mansoni and haematobium files have to be changed to 14 before the runs are set off. Additionally depending on the files being used the `drugEff2` should be updated too

2024-10-22 11:49 UTC, igorclark commented
brilliant thanks @mattg3004

yes that's right, i'm using `SCH_params/202410b-20241021` for this run so only the ones in there need updating, as per the new commit. `drugEff2` is already at 0.99. and yes, no need to update STH, just wanted to leave the most recent ones there rather than overwrite from the AMIS branch.

```
$ grep -E '(drugEff2|nYears)' sch_simulation/data/SCH_params/202410b-20241021/*params.txt
sch_simulation/data/SCH_params/202410b-20241021/haematobium_params.txt:nYears   14              Number of years to run
sch_simulation/data/SCH_params/202410b-20241021/haematobium_params.txt:drugEff2 0.99                                    Drug efficacy  drug 2
sch_simulation/data/SCH_params/202410b-20241021/mansoni_high_burden_params.txt:nYears   14              Number of years to run
sch_simulation/data/SCH_params/202410b-20241021/mansoni_high_burden_params.txt:drugEff2 0.99                                    Drug efficacy  drug 2
sch_simulation/data/SCH_params/202410b-20241021/mansoni_low_burden_params.txt:nYears    14              Number of years to run
sch_simulation/data/SCH_params/202410b-20241021/mansoni_low_burden_params.txt:drugEff2  0.99                                    Drug efficacy  drug 2
```

2024-10-22 11:49 UTC, igorclark commented on sch_simulation/data/SCH_params/202410b-20241021/haematobium_params.txt
> +nYears	39		Number of years to run
done

2024-10-22 11:49 UTC, igorclark commented on sch_simulation/data/SCH_params/202410b-20241021/mansoni_low_burden_params.txt
> +nYears	39		Number of years to run
done

2024-10-22 11:49 UTC, igorclark commented on sch_simulation/data/SCH_params/202410b-20241021/mansoni_high_burden_params.txt
> +nYears	39		Number of years to run
done

2024-10-24 02:26 UTC, mattg3004 approved these changes

2024-10-24 03:05 UTC, igorclark commented
hi @thk123, the `3.10.9` CI build is succeeding now but the PR can't be merged because it's expecting `3.10` and `3.9` builds, how do we clear these out?

<img width="845" alt="Screenshot 2024-10-23 at 22 59 39" src="https://github.com/user-attachments/assets/616fc787-0cca-42c0-8b05-e393a6569ccc">

2024-10-24 10:44 UTC, thk123 commented
I've removed that requirement - I'll have a think about how to make it work better, but now is not the time,  we can just trust that people won't merge if CI is failing! 

As a side note, it is very annoying that you can't simply specify that the CI that run should pass!!

2024-10-24 12:42 UTC, igorclark commented
thanks @thk123 !

2024-10-24 12:50 UTC, merged